version: "3"
services:
  gcloud:
    build: .
    volumes:
      - ./mygcloud:/config/mygcloud
      - ./home:/home/gcloud
      - ./home/.config/starship.toml:/home/gcloud/.config/starship.toml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CLOUDSDK_CONFIG=/config/mygcloud
    command: /bin/bash
