version: "3"
services:
  gcloud:
    build: .
    working_dir: /root
    volumes:
      - ./mygcloud:/config/mygcloud
      - ./home:/root
      - ./home/.config/starship.toml:/root/.config/starship.toml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CLOUDSDK_CONFIG=/config/mygcloud
    command: /bin/bash
